# Generated by Django 4.0.3 on 2022-03-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_flashcard_created_at_alter_deck_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='correct',
            field=models.BooleanField(default='0'),
        ),
    ]
