# Generated by Django 4.0.3 on 2022-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_flashcard_created_at_alter_deck_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, unique=True),
        ),
    ]
